/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/ioc/search/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * IoC reputation enrichment for a URL.
         * @description Returns reputation, detections, categories, and network relationships
         *     for the supplied URL.
         */
        get: operations["vectorSnapUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ioc/search/hash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * IoC reputation enrichment for a file hash.
         * @description Returns file analysis for the supplied hash (MD5, SHA-1, or SHA-256
         *     accepted; resolved to SHA-256).
         */
        get: operations["vectorSnapHash"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ioc/search/ip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * IoC reputation enrichment for an IPv4 address.
         * @description Returns reputation, WHOIS, ASN, and relationship data for the supplied
         *     IPv4 address.
         */
        get: operations["vectorSnapIp"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ioc/search/domain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * IoC reputation enrichment for a domain.
         * @description Returns reputation, WHOIS, DNS records, certificates, categories, and
         *     relationships for the supplied domain.
         */
        get: operations["vectorSnapDomain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pulse-snap/scan/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Threat-intelligence pulse enrichment for a URL.
         * @description Pulse summary for the supplied URL.
         */
        get: operations["pulseSnapUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pulse-snap/scan/hash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Threat-intelligence pulse and sandbox enrichment for a file hash.
         * @description Pulse summary plus sandbox analysis for the supplied file hash.
         */
        get: operations["pulseSnapHash"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pulse-snap/scan/ip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Threat-intelligence pulse enrichment for an IPv4 address.
         * @description Pulse summary, associated malware, and passive DNS for the supplied
         *     IPv4 address.
         */
        get: operations["pulseSnapIp"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pulse-snap/scan/domain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Threat-intelligence pulse enrichment for a domain.
         * @description Pulse summary, associated malware, and passive DNS for the supplied
         *     domain.
         */
        get: operations["pulseSnapDomain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subdo-snap/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Paginated subdomain enumeration for a domain.
         * @description Enumerates known subdomains for the supplied domain. Results are
         *     paginated: when more pages are available the response `data.cursor`
         *     is non-empty — pass it back as the `cursor` query parameter to fetch
         *     the next page.
         */
        get: operations["subdoSnapScan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The envelope wrapping every CrawlSnap API response. Inspect
         *     `is_success` before reading `data`.
         */
        BaseResponse: {
            /**
             * @description Endpoint-specific payload, refined per endpoint via allOf wrappers.
             *     Null on failure (`is_success: false`).
             */
            data?: unknown;
            /** @description True only when `data` contains usable enrichment. */
            is_success: boolean;
            /** @description Human-readable summary of the outcome. */
            message: string;
            /**
             * Format: int32
             * @description Mirrors the HTTP status code.
             */
            response_code: number;
        };
        /**
         * @description Error envelope. Shares the BaseResponse shape; `data` is always null
         *     and `is_success` is always false.
         */
        ErrorResponse: {
            /** @example null */
            data?: unknown;
            /** @example false */
            is_success: boolean;
            /** @example Invalid or inactive API key */
            message: string;
            /**
             * Format: int32
             * @example 401
             */
            response_code: number;
        };
        VectorSnapUrlResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["IocUrlScanData"];
        };
        VectorSnapHashResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["IocHashScanData"];
        };
        VectorSnapIpResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["IocIpScanData"];
        };
        VectorSnapDomainResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["IocDomainScanData"];
        };
        PulseSnapUrlResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["PulseUrlScanData"];
        };
        PulseSnapHashResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["PulseHashScanData"];
        };
        PulseSnapIpResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["PulseIpScanData"];
        };
        PulseSnapDomainResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["PulseDomainScanData"];
        };
        SubdoSnapScanResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["SubdoSnapScanData"];
        };
        IocUrlScanData: {
            /** @description SHA-256 of the queried URL. */
            hash_id: string;
            /** @enum {string} */
            search_type: "url";
            /** Format: uri */
            url?: string;
            /**
             * Format: int64
             * @description Unix timestamp of the last upstream modification.
             */
            modification_date?: number;
            /** Format: int64 */
            analysis_date?: number;
            reputation?: number;
            threat_names?: string[];
            tags?: string[];
            /** @description Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form. */
            categories?: unknown;
            /** @description Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form. */
            security_vendor_analysis?: unknown;
            /** @description Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form. */
            security_vendor_analysis_stats?: unknown;
            /** @description Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form. */
            url_content?: unknown;
            /** @description Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form. */
            network?: unknown;
        };
        IocHashScanData: {
            /** @description SHA-256 of the queried hash (resolved upstream when md5/sha1 supplied). */
            hash_id: string;
            /** @enum {string} */
            search_type: "hash";
            ssdeep?: string;
            type_tag?: string;
            type_tags?: string[];
            magic?: string;
            magika?: string;
            type_description?: string;
            meaningful_name?: string;
            authentihash?: string;
            /** @description Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form. */
            detectiteasy?: unknown;
            trid?: {
                [key: string]: unknown;
            }[];
            type_extension?: string;
            tags?: string[];
            tlsh?: string;
            /** Format: int64 */
            analysis_date?: number;
            /** Format: int64 */
            modification_date?: number;
            md5?: string;
            sha1?: string;
            sha256?: string;
            /** Format: int64 */
            file_size?: number;
            dropped_files?: {
                [key: string]: unknown;
            }[];
            bundled_files?: {
                [key: string]: unknown;
            }[];
            contacted_ips?: {
                [key: string]: unknown;
            }[];
            contacted_domains?: {
                [key: string]: unknown;
            }[];
            /** @description Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form. */
            sigma?: unknown;
            /** @description Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form. */
            sigma_stats?: unknown;
            /** @description Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form. */
            classification?: unknown;
            /** @description Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form. */
            pe_info?: unknown;
            /** @description Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form. */
            signature?: unknown;
            /** @description Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form. */
            votes_result?: unknown;
            /** @description Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form. */
            sandbox_verdicts?: unknown;
            /** @description Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form. */
            security_vendor_analysis?: unknown;
            /** @description Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form. */
            security_vendor_analysis_stats?: unknown;
        };
        IocIpScanData: {
            hash_id: string;
            /** @enum {string} */
            search_type: "ip";
            ip?: string;
            country?: string;
            reputation?: number;
            tags?: string[];
            whois?: string;
            /** Format: int64 */
            whois_update_date?: number;
            /** Format: int64 */
            asn?: number;
            as_owner?: string;
            network?: string;
            internet_registry?: string;
            continent?: string;
            /** Format: int64 */
            modification_date?: number;
            /** Format: int64 */
            analysis_date?: number;
            /** @description Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form. */
            votes_result?: unknown;
            /** @description Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form. */
            security_vendor_analysis?: unknown;
            /** @description Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form. */
            security_vendor_analysis_stats?: unknown;
            referrerFiles?: {
                [key: string]: unknown;
            }[];
            communicating_files?: {
                [key: string]: unknown;
            }[];
            resolutions?: {
                [key: string]: unknown;
            }[];
        };
        IocDomainScanData: {
            hash_id: string;
            /** @enum {string} */
            search_type: "domain";
            domain?: string;
            reputation?: number;
            tags?: string[];
            whois?: string;
            /** Format: int64 */
            whois_update_date?: number;
            /** Format: int64 */
            modification_date?: number;
            tld?: string;
            /** Format: int64 */
            dns_records_update_date?: number;
            /** Format: int64 */
            http_certificate_update_date?: number;
            jarm?: string;
            registrar?: string;
            /** Format: int64 */
            analysis_date?: number;
            /** @description Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form. */
            votes_result?: unknown;
            /** @description Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form. */
            security_vendor_analysis?: unknown;
            /** @description Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form. */
            security_vendor_analysis_stats?: unknown;
            /** @description Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form. */
            categories?: unknown;
            /** @description Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form. */
            popularity_ranks?: unknown;
            dns_records?: {
                [key: string]: unknown;
            }[];
            /** @description Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form. */
            http_certificate?: unknown;
            referrerFiles?: {
                [key: string]: unknown;
            }[];
            communicating_files?: {
                [key: string]: unknown;
            }[];
            subdomains?: {
                [key: string]: unknown;
            }[];
            resolutions?: {
                [key: string]: unknown;
            }[];
            siblings?: {
                [key: string]: unknown;
            }[];
        };
        PulseUrlScanData: {
            /** @description SHA-256 of the queried URL. */
            crawlsnap_hash_id: string;
            /** @enum {string} */
            search_type: "url";
            /**
             * @description Threat-intelligence pulse summary. Inner shape evolves upstream
             *     and is intentionally free-form.
             */
            pulse_detail?: {
                [key: string]: unknown;
            };
        };
        PulseHashScanData: {
            crawlsnap_hash_id: string;
            /** @enum {string} */
            search_type: "hash";
            pulse_detail?: {
                [key: string]: unknown;
            };
            /**
             * @description Sandbox analysis output (free-form). Curated before return/cache:
             *     low-value raw dumps are removed and long-tail arrays capped; all
             *     IOCs are preserved.
             */
            analysis?: {
                [key: string]: unknown;
            };
        };
        PulseIpScanData: {
            crawlsnap_hash_id: string;
            /** @enum {string} */
            search_type: "ip";
            pulse_detail?: {
                [key: string]: unknown;
            };
            malware?: {
                [key: string]: unknown;
            }[];
            passive_dns?: {
                [key: string]: unknown;
            }[];
        };
        PulseDomainScanData: {
            crawlsnap_hash_id: string;
            /** @enum {string} */
            search_type: "domain";
            pulse_detail?: {
                [key: string]: unknown;
            };
            malware?: {
                [key: string]: unknown;
            }[];
            passive_dns?: {
                [key: string]: unknown;
            }[];
        };
        SubdoSnapScanData: {
            hash_id: string;
            /** @enum {string} */
            search_type: "domain";
            subdomains?: {
                [key: string]: unknown;
            }[];
            /** @description Opaque pagination cursor for the next page (empty when no more pages). */
            cursor?: string;
            /**
             * Format: int64
             * @description Total subdomain count reported by upstream.
             */
            count?: number;
        };
    };
    responses: {
        /** @description Invalid input — malformed URL, hash, IP, or domain. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Missing or invalid API key. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Out of credits, or the subscription's monthly quota is exceeded. */
        PaymentRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The subscription tied to this key is not active. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description No IoC data was found for the supplied indicator. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The API key's daily request limit has been exceeded. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unexpected server-side failure. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The upstream enrichment service was unavailable. */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The upstream enrichment service timed out. */
        GatewayTimeout: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /**
         * @description The URL to enrich.
         * @example https://example.com
         */
        UrlQueryParam: string;
        /**
         * @description The file hash to enrich (MD5, SHA-1, or SHA-256).
         * @example 44d88612fea8a8f36de82e1278abb02f
         */
        HashQueryParam: string;
        /**
         * @description The IPv4 address to enrich.
         * @example 8.8.8.8
         */
        IpQueryParam: string;
        /**
         * @description The domain to enrich.
         * @example google.com
         */
        DomainQueryParam: string;
        /**
         * @description Opaque pagination cursor returned as `data.cursor` by a previous
         *     response. Omit on the first request.
         */
        CursorParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    vectorSnapUrl: {
        parameters: {
            query: {
                /**
                 * @description The URL to enrich.
                 * @example https://example.com
                 */
                query: components["parameters"]["UrlQueryParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful enrichment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VectorSnapUrlResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
            504: components["responses"]["GatewayTimeout"];
        };
    };
    vectorSnapHash: {
        parameters: {
            query: {
                /**
                 * @description The file hash to enrich (MD5, SHA-1, or SHA-256).
                 * @example 44d88612fea8a8f36de82e1278abb02f
                 */
                query: components["parameters"]["HashQueryParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful enrichment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VectorSnapHashResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
            504: components["responses"]["GatewayTimeout"];
        };
    };
    vectorSnapIp: {
        parameters: {
            query: {
                /**
                 * @description The IPv4 address to enrich.
                 * @example 8.8.8.8
                 */
                query: components["parameters"]["IpQueryParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful enrichment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VectorSnapIpResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
            504: components["responses"]["GatewayTimeout"];
        };
    };
    vectorSnapDomain: {
        parameters: {
            query: {
                /**
                 * @description The domain to enrich.
                 * @example google.com
                 */
                query: components["parameters"]["DomainQueryParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful enrichment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VectorSnapDomainResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
            504: components["responses"]["GatewayTimeout"];
        };
    };
    pulseSnapUrl: {
        parameters: {
            query: {
                /**
                 * @description The URL to enrich.
                 * @example https://example.com
                 */
                query: components["parameters"]["UrlQueryParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful enrichment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PulseSnapUrlResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
            504: components["responses"]["GatewayTimeout"];
        };
    };
    pulseSnapHash: {
        parameters: {
            query: {
                /**
                 * @description The file hash to enrich (MD5, SHA-1, or SHA-256).
                 * @example 44d88612fea8a8f36de82e1278abb02f
                 */
                query: components["parameters"]["HashQueryParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful enrichment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PulseSnapHashResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
            504: components["responses"]["GatewayTimeout"];
        };
    };
    pulseSnapIp: {
        parameters: {
            query: {
                /**
                 * @description The IPv4 address to enrich.
                 * @example 8.8.8.8
                 */
                query: components["parameters"]["IpQueryParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful enrichment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PulseSnapIpResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
            504: components["responses"]["GatewayTimeout"];
        };
    };
    pulseSnapDomain: {
        parameters: {
            query: {
                /**
                 * @description The domain to enrich.
                 * @example google.com
                 */
                query: components["parameters"]["DomainQueryParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful enrichment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PulseSnapDomainResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
            504: components["responses"]["GatewayTimeout"];
        };
    };
    subdoSnapScan: {
        parameters: {
            query: {
                /**
                 * @description The domain to enrich.
                 * @example google.com
                 */
                query: components["parameters"]["DomainQueryParam"];
                /**
                 * @description Opaque pagination cursor returned as `data.cursor` by a previous
                 *     response. Omit on the first request.
                 */
                cursor?: components["parameters"]["CursorParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful enumeration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubdoSnapScanResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
            504: components["responses"]["GatewayTimeout"];
        };
    };
}
